# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171017_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=b'static/images/posts/<function upload_location at 0x10ec975f0>', width_field=b'width_field'),
        ),
    ]
