# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 07:12
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171017_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=blog.models.upload_location, width_field=b'width_field'),
        ),
    ]
