# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171017_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
